# Generated by Django 5.1 on 2025-05-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bus',
            fields=[
                ('busno', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('busname', models.CharField(max_length=255)),
                ('seats_available', models.IntegerField(default=30)),
                ('Drivername', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('ticketno', models.IntegerField(primary_key=True, serialize=False)),
                ('Customer_name', models.CharField(max_length=255)),
                ('seatno', models.IntegerField(default=0)),
                ('busno', models.IntegerField(default=0)),
                ('destination', models.CharField(max_length=255)),
            ],
        ),
    ]
