# Generated by Django 5.2.1 on 2025-06-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tester',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('integer', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='Id_number',
            field=models.IntegerField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='destination',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
