# Generated by Django 5.1 on 2025-06-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_tester_customer_id_number_alter_customer_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(default='not paid', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Id_number',
            field=models.IntegerField(max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='seatno',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
