# Generated by Django 5.1 on 2025-06-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_customer_status_alter_customer_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Id_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
