# Generated by Django 5.2.1 on 2025-06-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_customer_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='busno',
            field=models.CharField(default=0, primary_key=True, serialize=False),
        ),
    ]
