# Generated by Django 5.2.1 on 2025-06-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_bus_busno'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='Destination',
            field=models.CharField(default='Nairobi', max_length=255),
        ),
    ]
